// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice8_26_2025_Copy.Data;

#nullable disable

namespace Practice8_26_2025_Copy.Migrations
{
    [DbContext(typeof(ComputerDbContext))]
    [Migration("20250826191556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Practice8_26_2025_Copy.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("RamGB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageGB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearManufactured")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Dell",
                            DateAdded = new DateTime(2025, 7, 27, 14, 15, 55, 433, DateTimeKind.Local).AddTicks(9438),
                            IsActive = true,
                            Model = "Latitude 5520",
                            Notes = "Corporate laptop - IT Department",
                            OperatingSystem = "Windows 11 Pro",
                            Processor = "Intel Core i7-1185G7",
                            PurchasePrice = 1299.99m,
                            RamGB = 16,
                            StorageGB = 512,
                            StorageType = "SSD",
                            YearManufactured = 2021
                        },
                        new
                        {
                            Id = 2,
                            Brand = "HP",
                            DateAdded = new DateTime(2025, 7, 12, 14, 15, 55, 433, DateTimeKind.Local).AddTicks(9446),
                            IsActive = true,
                            Model = "EliteBook 840 G8",
                            Notes = "Sales team laptop",
                            OperatingSystem = "Windows 10 Pro",
                            Processor = "Intel Core i5-1135G7",
                            PurchasePrice = 899.99m,
                            RamGB = 8,
                            StorageGB = 256,
                            StorageType = "SSD",
                            YearManufactured = 2020
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Apple",
                            DateAdded = new DateTime(2025, 6, 27, 14, 15, 55, 433, DateTimeKind.Local).AddTicks(9450),
                            IsActive = true,
                            Model = "MacBook Pro 13",
                            Notes = "Design team - Creative Suite",
                            OperatingSystem = "macOS Monterey",
                            Processor = "Apple M1",
                            PurchasePrice = 1499.99m,
                            RamGB = 16,
                            StorageGB = 512,
                            StorageType = "SSD",
                            YearManufactured = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
